### ISSUE TITLE
Cryptical ]] found in CmakeLists.txt

### ISSUE THREAD

**Issue by dominiKoeppl** [tudocomp/tudocomp#2]
Is there a reason behind the ']]' in line 20, /src/tudocomp_driver/CMakeLists.txt ?
The closing brackets match the opening brackets in line 1, but these are commented out.
Interestingly, cmake only compiles the CMakeLists.txt if either both brackets are deleted, or both are present.
Is this a cmake bug?

**Comment by Kimundi** [comment]
These are multi-line comments, apparently too new to not cause issues :) 
The offending lines are removed in current master.
